"use client";

import { use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { db } from "@/lib/db";
import { callManageStaff, fetchStaffMember, ManageStaffError, type StaffListItem } from "@/features/auth/manage-staff-client";
import { ScreenHeader } from "@/components/ui/ScreenHeader";
import { Skeleton } from "@/components/ui/Skeleton";
import { PermissionDenied } from "@/components/ui/PermissionDenied";
import { ErrorState } from "@/components/ui/ErrorState";
import { useToast } from "@/components/ui/Toast";
import { RippleButton } from "@/components/ui/Ripple";
import { useCurrentUser } from "@/features/auth/use-current-user";

interface PageProps { params: Promise<{ id: string }> }

export default function StaffDetailPage({ params }: PageProps) {
  const { id } = use(params);
  const router = useRouter();
  const user = useCurrentUser();
  const { showToast } = useToast();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [staffMember, setStaffMember] = useState<StaffListItem | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    let cancelled = false;
    fetchStaffMember(id).then((member) => { if (!cancelled) setStaffMember(member); }).catch(() => { if (!cancelled) setStaffMember(null); }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [id]);

  if (user.accountType !== "BUSINESS_OWNER") return <PermissionDenied requiredAccountType="BUSINESS_OWNER" />;
  if (loading) return <Skeleton className="h-40" />;
  if (!staffMember) return <ErrorState message="Could not find this staff member." onRetry={() => router.push("/staff")} />;
  const member = staffMember;
  const memberAccountType = member.accountType;

  const canModify = user.accountType === "BUSINESS_OWNER";

  async function resetWorkerPassword() {
    setError(null);
    setBusy(true);
    try {
      await callManageStaff({ action: "reset_password", userId: member.id });
      showToast("A new password was emailed to the worker.", "success");
    } catch (err) {
      setError(err instanceof ManageStaffError ? err.message : "Could not rotate the worker password.");
    } finally { setBusy(false); }
  }

  async function deactivate() {
    if (!confirm(`Deactivate ${member.fullName}? They will no longer be able to sign in.`)) return;
    setBusy(true);
    try {
      await callManageStaff({ action: "deactivate", userId: member.id });
      await db.localUsers.update(member.id, { isActive: false, updatedAt: new Date().toISOString() });
      showToast(`${member.fullName} deactivated`, "success");
      router.push("/staff");
    } catch (err) { setError(err instanceof ManageStaffError ? err.message : "Could not deactivate worker."); }
    finally { setBusy(false); }
  }

  async function reactivate() {
    setBusy(true);
    try {
      await callManageStaff({ action: "reactivate", userId: member.id });
      await db.localUsers.update(member.id, { isActive: true, updatedAt: new Date().toISOString() });
      showToast(`${member.fullName} reactivated`, "success");
      router.push("/staff");
    } catch (err) { setError(err instanceof ManageStaffError ? err.message : "Could not reactivate worker."); }
    finally { setBusy(false); }
  }

  return <div className="flex flex-col gap-6">
    <ScreenHeader title={staffMember.fullName} onBack={() => router.push("/staff")} />
    {error && <div className="rounded-[var(--radius-card)] bg-danger-container px-4 py-3 text-on-danger-container">{error}</div>}
    <section>
      <h2 className="mb-2 text-[length:var(--font-size-label)] font-medium text-on-surface-muted">Account type</h2>
      <p className="text-[length:var(--font-size-body)] text-on-surface">{memberAccountType === "BUSINESS_OWNER" ? "Business Owner" : "Worker"}</p>
    </section>
    {memberAccountType === "WORKER" && <section>
      <h2 className="mb-2 text-[length:var(--font-size-label)] font-semibold text-on-surface-muted uppercase tracking-wide">Worker password</h2>
      <div className="flex flex-col gap-2 rounded-[var(--radius-card)] border border-border bg-surface-container/40 p-4">
        <p className="text-[length:var(--font-size-body)] text-on-surface">The password is generated by StockPadi and delivered privately to the worker&apos;s email.</p>
        <RippleButton type="button" onClick={resetWorkerPassword} disabled={busy || !canModify} className="min-h-[var(--touch-target-min)] w-full rounded-[var(--radius-control)] border border-brand-accent px-4 font-semibold text-brand-accent disabled:opacity-50">
          {busy ? "Sending…" : "Generate and email new password"}
        </RippleButton>
      </div>
    </section>}
    {memberAccountType === "WORKER" && staffMember.isActive && <button type="button" onClick={deactivate} disabled={busy || !canModify} className="min-h-[var(--touch-target-min)] rounded-[var(--radius-control)] border border-danger px-4 text-danger disabled:opacity-50">Deactivate</button>}
    {memberAccountType === "WORKER" && !staffMember.isActive && <button type="button" onClick={reactivate} disabled={busy || !canModify} className="min-h-[var(--touch-target-min)] rounded-[var(--radius-control)] border border-brand-accent px-4 text-brand-accent disabled:opacity-50">Reactivate</button>}
  </div>;
}
